version: "3"

services:

  # SA-MP Server
  samp:
    build: .                          # Build image from Dockerfile
    entrypoint: sampctl p run         # Start server
    ports:
      - "7777:7777/udp"               # Expose port 7777 to allow UDP connections form outside container
    depends_on:
      - samp_db                       # Mark container service 'samp_db' as dependency
    container_name: samp              # Container name
    volumes:                          # Volume for runtime dependencies (Plugins, SA-MP server binaries)
      - runtime-dependencies:/root/.samp
    environment:                      # Add environment variables
      MYSQL_HOST: samp_db             # Use container name 'samp_db' of container service 'samp_db' as database host
      MYSQL_USER: samp
      MYSQL_PASSWORD: db_password
      MYSQL_DATABASE: cnr

  # MySQL Database
  samp_db:
    image: mysql                      # Latest MySQL runtime as parent image
    command:                          # Disable caching_sha2_password plugin to allow SA-MP server to connect
      --default-authentication-plugin=mysql_native_password
    volumes:                          # Bind mount for file './sql.sql' on host to file '/docker-entrypoint-initdb.d/sql.sql' in container
      - ./sql.sql:/docker-entrypoint-initdb.d/sql.sql
    container_name: samp_db           # Container name
    environment:                      # Add environment variables
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: samp
      MYSQL_PASSWORD: db_password
      MYSQL_DATABASE: cnr

volumes:
  runtime-dependencies:               # Volume for runtime dependencies (Plugins, SA-MP server binaries)

# Command to start all services at once
# docker-compose up

# Commands to enter running containers
# docker exec -it samp bash
# docker exec -it samp_db mysql -u root -p
